<a href="https://colab.research.google.com/github/nicoduoc20/Clases-Mineria-Dato/blob/main/clase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max.rows',300) #capacidad del valor

In [ ]:
df = pd.read_csv("1.4.4_superstore.csv")

In [ ]:
df.head()

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
0,21865-109365-13542,109365,21865,Xerox 22,Paper,Office Supplies,0.0,2016-11-03,3,11,Thursday,2016,3,Consumer,California,7267,15139
1,15745-162026-16405,162026,15745,Xerox 1925,Paper,Office Supplies,0.0,2016-10-08,8,10,Saturday,2016,2,Consumer,California,21713,48251
2,10090-136448-10461,136448,10090,Logitech 910-002974 M325 Wireless Mouse for We...,Accessories,Technology,0.2,2017-09-16,16,9,Saturday,2017,2,Consumer,Pennsylvania,11210,37368
3,16525-142993-23814,142993,16525,"Contico 72""H Heavy-Duty Storage System",Storage,Office Supplies,0.0,2015-10-12,12,10,Monday,2015,2,Consumer,Washington,0,63826
4,15280-115819-4927,115819,15280,PowerGen Dual USB Car Charger,Phones,Technology,0.2,2016-04-19,19,4,Tuesday,2016,5,Consumer,California,10114,31119

In [ ]:
df.columns

Index(['Transaction ID', 'Order ID', 'Customer ID', 'Product Name',
       'Sub-Category', 'Category', 'Discount', 'Order Date', 'Order Day',
       'Order Month', 'Order Weekday', 'Order Year', 'Quantity', 'Segment',
       'State', 'Profit CLP', 'Sales CLP'],
      dtype='object')

In [ ]:
df['Category'].value_counts()

Category
Office Supplies    6026
Furniture          2120
Technology         1847
Name: count, dtype: int64

In [ ]:
df['Product Name'].value_counts()

Product Name
Staple envelope                         48
Staples                                 46
Easy-staple paper                       46
Avery Non-Stick Binders                 20
Staples in misc. colors                 19
                                        ..
Linden 12" Wall Clock With Oak Frame     1
Plantronics Single Ear Headset           1
4009 Highlighters                        1
Grip Seal Envelopes                      1
Xerox Blank Computer Paper               1
Name: count, Length: 1850, dtype: int64

In [ ]:
df.isnull().sum() #Para ver los valores null por fila

Transaction ID    0
Order ID          0
Customer ID       0
Product Name      0
Sub-Category      0
Category          0
Discount          0
Order Date        0
Order Day         0
Order Month       0
Order Weekday     0
Order Year        0
Quantity          0
Segment           0
State             0
Profit CLP        0
Sales CLP         0
dtype: int64

In [ ]:
df.describe().round() #Toma todas las columnas numericas y obtiene estadisticas

,Order ID,Customer ID,Discount,Order Day,Order Month,Order Year,Quantity,Profit CLP,Sales CLP
count,9993.0,9993.0,9993.0,9993.0,9993.0,9993.0,9993.0,9993.0,9993.0
mean,134438.0,16038.0,0.0,15.0,8.0,2016.0,4.0,22320.0,178998.0
std,20253.0,3429.0,0.0,9.0,3.0,1.0,2.0,182439.0,485376.0
min,100006.0,10015.0,0.0,1.0,1.0,2014.0,1.0,-5139733.0,346.0
25%,117156.0,13045.0,0.0,8.0,5.0,2015.0,2.0,1348.0,13457.0
50%,133613.0,16120.0,0.0,15.0,9.0,2016.0,3.0,6753.0,42426.0
75%,152072.0,18985.0,0.0,23.0,11.0,2017.0,5.0,22867.0,163491.0
max,169999.0,21925.0,1.0,31.0,12.0,2017.0,14.0,6541481.0,17629716.0

In [ ]:
df_limpio = df.dropna() #Elimina los valores nulos

In [ ]:
df_limpio.to_csv("limpio.csv")